#ifndef CONSTANTS_H
#define CONSTANTS_H

#define DRAG_COEFFICIENT 0.006
#define TIME_STEP 0.01
#define GRAVITY_CONSTANT 9.81
#define MINIMUM_SPEED_KMH 3
#define MAXIMUM_SPEED_KMH 30
#define MAXIMUM_ROAD_SPEED_LIMIT_KMH 60

#define NUMBER_OF_BINS 1000
#define POINT_THRESHOLD 0.2

#define MINIMUM_ROUTE_DISTANCE 1000

#endif // CONSTANTS_H
